name: Java Spring Boot Pipeline

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: My first step
                run: |
         echo "This is DevOps Molvi"
         uname -a
        
        
    
